### ISSUE TITLE
config.json causes errors in the sniper

### ISSUE THREAD

**Issue by splurp** [aquild/arceus#2]
Works fine for benchmarking, but attempting to use config.json to transfer/block causes an error; tested with multiple accounts on multiple usernames.

https://i.imgur.com/DOnh2Ug.png

changing "account" to "accounts" inside of config.json fixes that error, but causes another:

https://i.imgur.com/9aRKwfO.png

**Comment by aquild** [comment]
@splurp I forgot to update the example config in the README. It's fixed now.
